import React, { useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons } from '@expo/vector-icons';

const projects = [
  ['Python HIL Automation Framework','Python · Pytest · dSPACE','Reduced repetitive manual HIL testing effort by about 40%.'],
  ['CAN / J1939 Validation','CAN · J1939 · CAPL · CANalyzer','Communication validation for embedded automotive systems.'],
  ['Display Validation Utility','OpenCV · OCR · Python','Automated GUI and text-rendering verification.'],
  ['API & Data Load Automation','Pytest · Postman · Katalon','Validated payloads, imports and backend interactions.']
];
const skills = ['Python','Pytest','dSPACE','CAN / J1939','CAPL','Robot Framework','Selenium','Postman','OpenCV','Tesseract OCR'];

export default function App() {
  const [tab,setTab] = useState('Home');
  const go = (url) => Linking.openURL(url);
  return <SafeAreaView style={s.safe}>
    <StatusBar style="light" />
    <View style={s.header}><View><Text style={s.kicker}>AUTOMOTIVE · HIL · QA</Text><Text style={s.brand}>MAYUR <Text style={s.purple}>KAMBLE</Text></Text></View><View style={s.avatar}><Text style={s.avatarText}>MK</Text></View></View>
    <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
      {tab === 'Home' && <>
        <View style={s.hero}><Text style={s.eyebrow}>TEST AUTOMATION ENGINEER</Text><Text style={s.title}>Engineering <Text style={s.purple}>confidence</Text> into every test.</Text><Text style={s.body}>I build automation systems that make embedded and web testing faster, repeatable and measurable — from HIL benches to backend APIs.</Text><View style={s.row}><Stat value="2+" label="Years"/><Stat value="40%" label="Effort reduced"/><Stat value="10+" label="Tools"/></View></View>
        <Section title="FOCUS"><Card icon="hardware-chip-outline" title="Automotive HIL" text="dSPACE AutomationDesk / ControlDesk, embedded validation and regression testing."/><Card icon="code-slash-outline" title="Python Automation" text="Reusable Pytest, Robot Framework and automation utilities."/><Card icon="git-network-outline" title="Web & API QA" text="JSON/XML payload validation, data-load testing and scalable automation."/></Section>
        <Section title="SELECTED WORK">{projects.map(p=><Project key={p[0]} p={p}/>)}</Section>
      </>}
      {tab === 'Skills' && <><Text style={s.pageTitle}>Toolkit</Text><Text style={s.body}>A practical stack spanning embedded testing, automation, protocols, computer vision and web QA.</Text><View style={s.chips}>{skills.map(x=><View style={s.chip} key={x}><Text style={s.chipText}>{x}</Text></View>)}</View></>}
      {tab === 'Experience' && <><Text style={s.pageTitle}>Experience</Text><Timeline year="2025 — PRESENT" title="Engineer — Web Automation" text="L&T Technology Services · API/data-load testing, JSON/XML validation and scalable automation architecture."/><Timeline year="2024 — 2025" title="Associate Engineer — HIL Testing" text="L&T Technology Services · Python HIL automation, dSPACE, CAN/J1939 and display validation."/><Timeline year="EDUCATION" title="B.Tech — Computer Science & Engineering" text="Rajarambapu Institute of Technology, Sangli · CGPA 7.59"/></>}
      {tab === 'Contact' && <><Text style={s.pageTitle}>Let's connect</Text><Text style={s.body}>Open to automotive test automation, HIL engineering and QA automation opportunities.</Text><Pressable style={s.contact} onPress={()=>go('mailto:mayur.pradeep.kamble@gmail.com')}><Ionicons name="mail-outline" size={22} color="#b56cff"/><Text style={s.contactText}>mayur.pradeep.kamble@gmail.com</Text></Pressable><Pressable style={s.contact} onPress={()=>go('https://github.com/demonk09')}><Ionicons name="logo-github" size={22} color="#b56cff"/><Text style={s.contactText}>GitHub</Text></Pressable><Pressable style={s.contact} onPress={()=>go('https://www.linkedin.com')}><Ionicons name="logo-linkedin" size={22} color="#b56cff"/><Text style={s.contactText}>LinkedIn</Text></Pressable></>}
    </ScrollView>
    <View style={s.nav}>{[['Home','home-outline'],['Skills','layers-outline'],['Experience','briefcase-outline'],['Contact','chatbubble-outline']].map(([name,icon])=><Pressable key={name} onPress={()=>setTab(name)} style={s.navItem}><Ionicons name={icon} size={22} color={tab===name?'#b56cff':'#777'}/><Text style={[s.navText,tab===name&&s.active]}>{name}</Text></Pressable>)}</View>
  </SafeAreaView>
}
function Stat({value,label}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Section({title,children}){return <View style={s.section}><Text style={s.sectionLabel}>{title}</Text>{children}</View>}
function Card({icon,title,text}){return <View style={s.card}><Ionicons name={icon} size={25} color="#b56cff"/><Text style={s.cardTitle}>{title}</Text><Text style={s.cardText}>{text}</Text></View>}
function Project({p}){return <View style={s.project}><View style={s.projectNum}><Text>WORK</Text></View><Text style={s.projectTitle}>{p[0]}</Text><Text style={s.projectTech}>{p[1]}</Text><Text style={s.cardText}>{p[2]}</Text></View>}
function Timeline({year,title,text}){return <View style={s.timeline}><Text style={s.year}>{year}</Text><View style={s.dot}/><Text style={s.cardTitle}>{title}</Text><Text style={s.cardText}>{text}</Text></View>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#08070a'},content:{padding:20,paddingBottom:120},header:{paddingHorizontal:20,paddingTop:10,paddingBottom:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,color:'#777',letterSpacing:2},brand:{fontSize:18,fontWeight:'800',color:'#f5f2fa',letterSpacing:1},purple:{color:'#b56cff'},avatar:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:'#3b264d',backgroundColor:'#17111c',alignItems:'center',justifyContent:'center'},avatarText:{color:'#b56cff',fontWeight:'800'},hero:{paddingTop:26,paddingBottom:28},eyebrow:{color:'#b56cff',fontSize:11,fontWeight:'700',letterSpacing:1.5,marginBottom:14},title:{fontSize:43,lineHeight:48,fontWeight:'800',color:'#f6f3f8'},body:{fontSize:15,lineHeight:23,color:'#96919d',marginTop:15},row:{flexDirection:'row',marginTop:26,gap:10},stat:{flex:1,padding:14,borderRadius:16,borderWidth:1,borderColor:'#29232e',backgroundColor:'#100d12'},statValue:{fontSize:25,fontWeight:'800',color:'#eee'},statLabel:{fontSize:10,color:'#777',marginTop:4},section:{marginTop:25},sectionLabel:{fontSize:10,letterSpacing:2,color:'#6f6876',marginBottom:13},card:{padding:18,borderRadius:18,borderWidth:1,borderColor:'#29232e',backgroundColor:'#100d12',marginBottom:10},cardTitle:{fontSize:17,fontWeight:'700',color:'#eee',marginTop:10},cardText:{fontSize:13,lineHeight:20,color:'#88818f',marginTop:7},project:{padding:18,borderRadius:18,borderWidth:1,borderColor:'#29232e',backgroundColor:'#100d12',marginBottom:10},projectNum:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:5,borderRadius:7,backgroundColor:'#1a1222'},projectNumText:{color:'#b56cff'},projectTitle:{fontSize:19,fontWeight:'750',color:'#eee',marginTop:13},projectTech:{fontSize:11,color:'#b56cff',marginTop:7},pageTitle:{fontSize:38,fontWeight:'800',color:'#f5f2fa',marginTop:20,marginBottom:5},chips:{flexDirection:'row',flexWrap:'wrap',gap:9,marginTop:25},chip:{paddingHorizontal:14,paddingVertical:11,borderRadius:14,borderWidth:1,borderColor:'#332a3a',backgroundColor:'#110e14'},chipText:{color:'#ddd',fontSize:13},timeline:{borderLeftWidth:1,borderLeftColor:'#392e42',paddingLeft:20,paddingBottom:30,marginTop:22,position:'relative'},dot:{position:'absolute',left:-5,top:0,width:9,height:9,borderRadius:5,backgroundColor:'#b56cff'},year:{fontSize:10,color:'#b56cff',letterSpacing:1.5,marginBottom:9},contact:{flexDirection:'row',alignItems:'center',gap:12,padding:17,borderRadius:16,borderWidth:1,borderColor:'#29232e',backgroundColor:'#100d12',marginTop:12},contactText:{color:'#ddd',fontSize:13,flex:1},nav:{position:'absolute',bottom:0,left:0,right:0,height:76,backgroundColor:'#0c0a0f',borderTopWidth:1,borderTopColor:'#252027',flexDirection:'row',justifyContent:'space-around',paddingTop:9},navItem:{alignItems:'center',width:'25%'},navText:{fontSize:9,color:'#777',marginTop:4},active:{color:'#b56cff',fontWeight:'700'}});
